const techs = [
    { nome: 'HTML5', img: require('../assets/tecnologias/html5.png') },
    { nome: 'CSS3', img: require('../assets/tecnologias/css3.png') },
    { nome: 'JavaScript', img: require('../assets/tecnologias/javascript.png') },
    { nome: 'Vue.Js', img: require('../assets/tecnologias/vuejs.png') },
    { nome: 'Bootstrap', img: require('../assets/tecnologias/bootstrap.png') },
    { nome: 'BootstrapVue', img: require('../assets/tecnologias/bootstrap-vue.png') },
    { nome: 'Quasar', img: require('../assets/tecnologias/quasar.png') },
    { nome: 'PrimeVue', img: require('../assets/tecnologias/primevue.png') },
    { nome: 'Vuetify', img: require('../assets/tecnologias/vuetify.png') },
    { nome: 'SASS', img: require('../assets/tecnologias/sass.png') },
    { nome: 'Linguagem C', img: require('../assets/tecnologias/c.png') },
    { nome: 'PHP', img: require('../assets/tecnologias/php.png') },
    { nome: 'Jquery', img: require('../assets/tecnologias/jquery.png') },
    { nome: 'NodeJs', img: require('../assets/tecnologias/nodejs.png') },
    { nome: 'MySql', img: require('../assets/tecnologias/mysql.png') },
    { nome: 'Scrum/Kanban', img: require('../assets/tecnologias/scrum.png') },
    { nome: 'Wordpress', img: require('../assets/tecnologias/wordpress.png') },
    { nome: 'Git/Github', img: require('../assets/tecnologias/github.png') },
    { nome: 'Netlify', img: require('../assets/tecnologias/netlify.png') }
]

const botoes = [
    { value: null, text: 'Vue.Js' },
    { value: 'Wordpress', text: 'Wordpress' },
    { value: 'Elementor', text: 'Elementor' },
    { value: 'Woocommerce', text: 'Woocommerce' },
    { value: 'HTML5', text: 'HTML5' },
    { value: 'CSS3', text: 'CSS3' },
    { value: 'JavaScript', text: 'JavaScript' },
    { value: 'Bootstrap', text: 'Bootstrap' },
    { value: 'BootstrapVue', text: 'BootstrapVue' },
    { value: 'Quasar', text: 'Quasar' },
    { value: 'PrimeVue', text: 'PrimeVue' },
    { value: 'Vuetify', text: 'Vuetify' },
    { value: 'Msw', text: 'Msw' },
    { value: 'Webdriver', text: 'Webdriver' },
    { value: 'Cypress', text: 'Cypress' },
    { value: 'PHP', text: 'PHP' },
    //{ value: 'Jquery', text: 'Jquery' },
    { value: 'Node.Js', text: 'Node.Js' },
    { value: 'Kotlin', text: 'Kotlin' },
    { value: 'Java', text: 'Java' },
    { value: 'MySql', text: 'MySql' },
    { value: 'Electron', text: 'Electron' },
    { value: 'Netlify', text: 'Netlify' },
    { value: 'Firebase', text: 'Firebase' }
]

export { techs, botoes };
